spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
spring:
  config:
    import: optional:configserver:http://config-server:8888
