version: '3.8'

services:
  config-server:
    image: config-server:latest
    build:
      context: ./config-server
    ports:
      - "8888:8888"

  discovery-server:
    image: discovery-server:latest
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  account-service:
    image: account-service:latest
    build:
      context: ./account-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-server

  transaction-service:
    image: transaction-service:latest
    build:
      context: ./transaction-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-server
  # api-gateway:
  #   image: api-gateway:latest
  #   build:
  #     context: ./api-gateway
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #   - config-server
  #   - discovery-server
